name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    # Run automatically every 24 hours
    - cron: "0 */24 * * *"

  # Allows to manually run the job at any time.
  workflow_dispatch:

  # Run on every push on the master branch
  push:
    branches:
      - main

# The sequence of runs in this workflow:
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    
    steps:
      # Generates the snake
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: AvrilMZ
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push the images to the output branch
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
